Algoritmo "múltiplos de 2 de 0 a 100"
// Disciplina   : [Introdução à Lógica de Programação]
// Professor   : Marcos Monteiro
// Crie um programa que apresente os múltiplos de dois entre 0 e 100.
// Autor(a)    : Leandro Morais
// Data atual  : 26/05/2022
Var
   // Seção de Declarações das variáveis
i : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

 para i de 0 ate 100 passo 2 faca
      escreval(i)
      fimpara

Fimalgoritmo